apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rhdhai-rhdh-dev-servicemonitor.yaml
  - rhdhai-rhdh-dev-prometheus-rules.yaml
  - alertmanager-config.yaml
  - podmonitor-lightspeed-stack.yaml
