apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rhdh-metrics
  namespace: rhdhai-development
spec:
  namespaceSelector:
    matchNames:
      - rhdhai-development
  selector:
    matchLabels:
      app.kubernetes.io/name: backstage
      app.kubernetes.io/instance: rhdhai-rhdh-dev
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
