apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-pruner-sa
  namespace: argocd-pruner-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-gitops-prunning-manager
  namespace: openshift-gitops
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-prunning-manager
  namespace: argocd-pruner-ns
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "create", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-prunning-manager-binding
  namespace: argocd-pruner-ns
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: argocd-prunning-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-gitops-prunning-manager-binding
  namespace: openshift-gitops
subjects:
  - kind: ServiceAccount
    name: argocd-pruner-sa
    namespace: argocd-pruner-ns
roleRef:
  kind: Role
  name: openshift-gitops-prunning-manager
  apiGroup: rbac.authorization.k8s.io
