kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redhat-ai-dev-view
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: redhat-ai-dev-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
