apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ollama-models-config.yaml
  - ollama-deployment.yaml
  - ollama-service.yaml
  - ollama-pvc.yaml
  - https://github.com/redhat-ai-dev/ollama-model-viewer/deploy?ref=main

namespace: ollama
