kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ollama-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
  
