apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    extraEnvs:
      secrets:
        - name: secrets-rhdh
    extraFiles:
      configMaps:
        - name: rhdh-rbac-policy
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
  deployment:
    patch:
      spec:
        template:
          spec:
            containers:
              - env:
                  - name: PROJECT
                    value: rhdh
                  - name: RCS_CONFIG_FILE
                    value: /app-root/config/rcsconfig.yaml
                  - name: RHDH_CONFIG_FILE
                    value: /app-root/config/app-config-rhdh.yaml
                envFrom:
                  - secretRef:
                      name: secrets-rhdh
                image: 'quay.io/redhat-ai-dev/road-core-service:latest'
                name: road-core-sidecar
                ports:
                  - containerPort: 8080
                    name: rcs-backend
                    protocol: TCP
                volumeMounts:
                  - mountPath: /app-root/config/rcsconfig.yaml
                    name: rcsconfig
                    subPath: rcsconfig.yaml
                  - mountPath: /app-root/config/app-config-rhdh.yaml
                    name: app-config-rhdh
                    subPath: app-config-rhdh.yaml
                  - mountPath: /app-root/tmp/data/feedback
                    name: shared-data
              - env:
                  - name: PGUSER
                    valueFrom:
                      secretKeyRef:
                        name: feedback-postgres-info
                        key: user
                  - name: PGPASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: feedback-postgres-info
                        key: password
                  - name: PGDATABASE
                    valueFrom:
                      secretKeyRef:
                        name: feedback-postgres-info
                        key: db-name
                  - name: PGHOST
                    value: feedback-postgres-svc.feedback-postgres.svc.cluster.local
                  - name: PGPORT
                    value: 5432
                  - name: FEEDBACK_DIRECTORY
                    value: /app-root/tmp/data/feedback
                  - name: FETCH_FREQUENCY
                    value: 60
                image: 'quay.io/redhat-ai-dev/feedback-harvester:v0.1.0'
                name: feedback-harvester
                volumeMounts:
                  - mountPath: /app-root/tmp/data/feedback
                    name: shared-data
            volumes:
              - configMap:
                  name: rcsconfig
                name: rcsconfig
              - name: shared-data
                emptyDir: {}
