kind: ConfigMap
apiVersion: v1
metadata:
  name: rhdh-lightspeed-rbac-policy
  labels:
    rhdh.redhat.com/ext-config-sync: 'true'
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  rbac-policy.csv: |
    p, role:default/lightspeed, lightspeed.conversations.read, read, allow
    p, role:default/lightspeed, lightspeed.conversations.create, create, allow
    p, role:default/lightspeed, lightspeed.conversations.delete, delete, allow

    g, user:default/afred, role:default/lightspeed
    g, user:default/bsutter, role:default/lightspeed
    g, user:default/bwilcock, role:default/lightspeed
    g, user:default/coreydaley, role:default/lightspeed
    g, user:default/esapram, role:default/lightspeed
    g, user:default/eyuen, role:default/lightspeed
    g, user:default/gmontero, role:default/lightspeed
    g, user:default/hiramchirino, role:default/lightspeed
    g, user:default/jcollier, role:default/lightspeed
    g, user:default/jdubrick, role:default/lightspeed
    g, user:default/jrichter, role:default/lightspeed
    g, user:default/jtest, role:default/lightspeed
    g, user:default/junzhang, role:default/lightspeed
    g, user:default/kjeeyar, role:default/lightspeed
    g, user:default/kkanova, role:default/lightspeed
    g, user:default/kmarchan, role:default/lightspeed
    g, user:default/lhaim, role:default/lightspeed
    g, user:default/llyman, role:default/lightspeed
    g, user:default/mariggan, role:default/lightspeed
    g, user:default/mfaisal, role:default/lightspeed
    g, user:default/mleonova, role:default/lightspeed
    g, user:default/mshaksho, role:default/lightspeed
    g, user:default/mvaldron, role:default/lightspeed
    g, user:default/nthoen, role:default/lightspeed
    g, user:default/priyankaabel, role:default/lightspeed
    g, user:default/rorai, role:default/lightspeed
    g, user:default/shirshbe, role:default/lightspeed
    g, user:default/testuser-no-google, role:default/lightspeed
    g, user:default/tma, role:default/lightspeed
    g, user:default/tpetkos, role:default/lightspeed
    g, user:default/vincetsugranes, role:default/lightspeed
    g, user:default/yangcao, role:default/lightspeed
    g, user:default/ygalanti, role:default/lightspeed
    g, user:default/yxing, role:default/lightspeed
