kind: Deployment
apiVersion: apps/v1
metadata:
  name: audio-to-text-model-server
  labels:
    app.kubernetes.io/instance: audio-to-text-model-server
    app.kubernetes.io/name: audio-to-text-model-server
    app.kubernetes.io/part-of: audio-to-text-model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: audio-to-text-model-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: audio-to-text-model-server
    spec:
      volumes:
        - name: model-file
          emptyDir: {}
      initContainers:
        - name: model-file
          image: 'quay.io/redhat-ai-dev/whisper-small:latest'
          command:
            - /usr/bin/install
            - /model/model.file
            - /shared/
          resources: {}
          volumeMounts:
            - name: model-file
              mountPath: /shared
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: app-model-service
          env:
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: '8000'
            - name: MODEL_PATH
              value: /model/model.file
            - name: CHAT_FORMAT
              value: openchat
          securityContext:
            runAsNonRoot: true
          ports:
            - containerPort: 8000
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: model-file
              mountPath: /model
          terminationMessagePolicy: File
          image: 'quay.io/redhat-ai-dev/whispercpp:latest'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

